name: Build and Push Docker Image to ECR

on: 
  workflow_dispatch:  # Allows manual triggering with custom inputs
    inputs:
      aws-account-id:
        description: 'AWS Account ID'
        required: true
        # default: 'live/dev/us-east-1/route53-hosted-zone'  # Default directory
        # tcw-ghActions-dev-terragrunt
      ecr-repo-name:
        description: 'Repo Name'
        required: true
      aws-region:
        description: 'AWS Region'
        required: true
      job:
        description: 'Build Job'
        required: true

jobs:
  build-and-push:
    runs-on: 
      -  codebuild-${{ github.event.inputs.job }}-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        env:
          AWS_REGION: "us-east-1"  # Replace with your AWS region
          AWS_ACCOUNT_ID: "${{ github.event.inputs.aws-account-id }}"
        run: |
          aws ecr get-login-password --region ${{ github.event.inputs.aws-region }} | docker login --username AWS --password-stdin ${{ github.event.inputs.aws-account-id }}.dkr.ecr.${{ github.event.inputs.aws-region }}.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t ${{ github.event.inputs.ecr-repo-name }}:${{ github.sha }} .
      
      - name: Tag Docker Image
        run: |
          docker tag ${{ github.event.inputs.ecr-repo-name }}:${{ github.sha }} ${{ github.event.inputs.aws-account-id }}.dkr.ecr.${{ github.event.inputs.aws-region }}.amazonaws.com/${{ github.event.inputs.ecr-repo-name }}:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ github.event.inputs.aws-account-id }}.dkr.ecr.${{ github.event.inputs.aws-region }}.amazonaws.com/${{ github.event.inputs.ecr-repo-name }}:latest

      - name: Clean up local Docker images
        run: |
          docker rmi ${{ github.event.inputs.ecr-repo-name }}:${{ github.sha }}
          docker rmi ${{ github.event.inputs.aws-account-id }}.dkr.ecr.${{ github.event.inputs.aws-region }}.amazonaws.com/${{ github.event.inputs.ecr-repo-name }}:latest